/**
 * Tests for the inline scripts of `.github/workflows/claude-code-review.yml`, run as the EXACT code the workflow
 * runs: each heredoc is extracted from the YAML, written to a temp file and executed with node against a synthetic
 * runner temp directory — the same file-based transport the workflow uses. Diff fixtures are generated by real
 * git from real commits (no hand-written hunks). Also tests the workflow's transport boundary (what may appear in
 * step env / with) and reproduces the action's `claude_args` parser locally.
 *
 * Proves: (a) only allowlisted enum/count lines and manifest-resolved indices/paths reach stdout — model-chosen
 * strings, sentinel secrets, URLs, commands, prose and paths never do; (b) missing / null / primitive / malformed /
 * oversized / refused / stale / incomplete / unresolvable inputs exit 1 and can never be relabelled as attested;
 * (c) the collector consumes every hunk body against its header and records old/new spans, so removed lines and
 * deleted files are addressable on the old side, and unsupported entries (binary, rename-only, mode-only) force
 * manual review; (d) any p1/p2 finding blocks (confidence >= 50) or requires manual review (< 50).
 */
import { execFileSync } from "node:child_process";
import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";

const require = createRequire(import.meta.url);
const yaml = require("js-yaml") as { load: (s: string) => unknown };
const shellQuote = require("shell-quote") as { parse: (s: string) => unknown[] };

const workflowPath = join(process.cwd(), ".github", "workflows", "claude-code-review.yml");
const workflow = readFileSync(workflowPath, "utf8");

function extractScript(marker: string): string {
  const start = `node - <<'${marker}'\n`;
  const end = `\n          ${marker}`;
  const startAt = workflow.indexOf(start);
  const endAt = workflow.indexOf(end, startAt);
  if (startAt < 0 || endAt < 0) throw new Error(`${marker} heredoc not found in workflow`);
  return workflow
    .slice(startAt + start.length, endAt)
    .split("\n")
    .map((l) => l.replace(/^ {10}/, ""))
    .join("\n");
}

const dir = mkdtempSync(join(tmpdir(), "ci-review-validator-"));
const validatorScript = join(dir, "validator.cjs");
writeFileSync(validatorScript, extractScript("CI_REVIEW_VALIDATOR"));
const manifestScript = join(dir, "manifest.cjs");
writeFileSync(manifestScript, extractScript("CI_REVIEW_MANIFEST"));

const HEAD = "b214a39c0b86b65a43d07f2c28700029706a4eb3";
const BASE = "d2bfd42bc763f92575d98305b13fb1b1af982c85";
const OTHER = "1134899e19aeae526b10f4f857027bd9ddfa734b";
const SENTINELS = [
  "sk-ant-api03-SENTINEL_SECRET",
  "https://sentinel.example/leak",
  "gh pr comment 151 --body SENTINEL",
  "PROSE_SENTINEL_TEXT",
  "/home/runner/SENTINEL_PATH",
];
const LINE = /^[a-z_-]+: [A-Za-z0-9_=.:/\- ]+$/;
const FILE_A = "src/lib/citation-authoring.ts";
const FILE_B = "src/lib/utc-instant.ts";

type Hunk = {
  oldSpan: [number, number] | null;
  newSpan: [number, number] | null;
  added: number;
  removed: number;
  context: number;
};
type Entry = {
  kind: string;
  oldPath: string | null;
  newPath: string | null;
  hunks: Hunk[];
  unsupported: string | null;
};
type Manifest = {
  head: string;
  base: string;
  files: Entry[];
  hunkCount: number;
  unsupported: number;
};

const DEFAULT_MANIFEST: Manifest = {
  head: HEAD,
  base: BASE,
  files: [
    {
      kind: "modify",
      oldPath: FILE_A,
      newPath: FILE_A,
      hunks: [{ oldSpan: [170, 180], newSpan: [170, 200], added: 25, removed: 5, context: 6 }],
      unsupported: null,
    },
    {
      kind: "add",
      oldPath: null,
      newPath: FILE_B,
      hunks: [{ oldSpan: null, newSpan: [1, 20], added: 20, removed: 0, context: 0 }],
      unsupported: null,
    },
  ],
  hunkCount: 2,
  unsupported: 0,
};
const withUnsupported = (m: Manifest, reason: string): Manifest => ({
  ...m,
  files: [
    ...m.files,
    { kind: "unsupported", oldPath: null, newPath: null, hunks: [], unsupported: reason },
  ],
  unsupported: m.unsupported + 1,
});

type Run = { code: number; out: string; lines: string[] };
type RunOptions = {
  structured?: unknown;
  execution?: unknown;
  executionRaw?: string;
  omitExecution?: boolean;
  manifest?: unknown;
  manifestRaw?: string;
  omitManifest?: boolean;
  stepOutcome?: string;
  expected?: string;
};

function completed(
  structured: unknown,
  denials: unknown[] = [],
  extra: Record<string, unknown> = {},
) {
  return [
    { type: "system", subtype: "init", cwd: SENTINELS[4] },
    {
      type: "assistant",
      message: {
        content: [
          { type: "text", text: SENTINELS[3] },
          { type: "tool_use", name: "Read", input: { file_path: SENTINELS[4] } },
        ],
      },
    },
    {
      type: "result",
      subtype: "success",
      is_error: false,
      num_turns: 7,
      result: SENTINELS[3] + SENTINELS[0],
      permission_denials: denials,
      structured_output: structured,
      ...extra,
    },
  ];
}
const reviewed = (findings: unknown[] = [], over: Record<string, unknown> = {}) => ({
  reviewedHeadSha: HEAD,
  outcome: "reviewed",
  filesInspected: 2,
  hunksInspected: 2,
  findings,
  ...over,
});
const finding = (over: Record<string, unknown> = {}) => ({
  category: "bug",
  severity: "p3",
  file: FILE_A,
  side: "new",
  line: 181,
  confidence: 85,
  ...over,
});

function runValidator(opts: RunOptions): Run {
  const runnerTemp = mkdtempSync(join(dir, "runner-temp-"));
  if (!opts.omitExecution) {
    const raw =
      opts.executionRaw !== undefined
        ? opts.executionRaw
        : JSON.stringify(
            opts.execution !== undefined ? opts.execution : completed(opts.structured),
          );
    writeFileSync(join(runnerTemp, "claude-execution-output.json"), raw);
  }
  if (!opts.omitManifest) {
    const raw =
      opts.manifestRaw !== undefined
        ? opts.manifestRaw
        : JSON.stringify(opts.manifest !== undefined ? opts.manifest : DEFAULT_MANIFEST);
    writeFileSync(join(runnerTemp, "pr-manifest.json"), raw);
  }
  const env: Record<string, string> = {
    PATH: process.env.PATH ?? "",
    REVIEW_STEP_OUTCOME: opts.stepOutcome ?? "success",
    RUNNER_TEMP_DIR: runnerTemp,
    EXPECTED_HEAD_SHA: opts.expected ?? HEAD,
  };
  try {
    const out = execFileSync(process.execPath, [validatorScript], { encoding: "utf8", env });
    return { code: 0, out, lines: out.trim().split("\n") };
  } catch (e) {
    const err = e as { status: number; stdout: string };
    return { code: err.status, out: err.stdout, lines: err.stdout.trim().split("\n") };
  }
}

function runManifest(diff: string, head = HEAD, base = BASE): Run & { manifest: Manifest | null } {
  const runnerTemp = mkdtempSync(join(dir, "manifest-temp-"));
  writeFileSync(join(runnerTemp, "pr.diff"), diff);
  const env = {
    PATH: process.env.PATH ?? "",
    RUNNER_TEMP_DIR: runnerTemp,
    HEAD_SHA: head,
    BASE_SHA: base,
  };
  let code = 0;
  let out = "";
  try {
    out = execFileSync(process.execPath, [manifestScript], { encoding: "utf8", env });
  } catch (e) {
    const err = e as { status: number; stdout: string };
    code = err.status;
    out = err.stdout;
  }
  let manifest: Manifest | null = null;
  try {
    manifest = JSON.parse(readFileSync(join(runnerTemp, "pr-manifest.json"), "utf8")) as Manifest;
  } catch {
    manifest = null;
  }
  return { code, out, lines: out.trim().split("\n"), manifest };
}

// Real git: base commit -> change -> head commit -> `git diff base head` (same unified format as GitHub's
// compare diff media type, rename detection on by default).
type Files = Record<string, string | Buffer>;
function realDiff(base: Files, change: (repo: string) => void): string {
  const repo = mkdtempSync(join(dir, "repo-"));
  const env = {
    PATH: process.env.PATH ?? "",
    HOME: repo,
    GIT_CONFIG_GLOBAL: "/dev/null",
    GIT_CONFIG_NOSYSTEM: "1",
    GIT_AUTHOR_NAME: "fixture",
    GIT_AUTHOR_EMAIL: "fixture@example.invalid",
    GIT_COMMITTER_NAME: "fixture",
    GIT_COMMITTER_EMAIL: "fixture@example.invalid",
  };
  const git = (...args: string[]) =>
    execFileSync("git", ["-c", "commit.gpgsign=false", ...args], {
      cwd: repo,
      encoding: "utf8",
      env,
    });
  git("init", "-q", "-b", "main");
  for (const [rel, content] of Object.entries(base)) {
    mkdirSync(dirname(join(repo, rel)), { recursive: true });
    writeFileSync(join(repo, rel), content);
  }
  git("add", "-A");
  git("commit", "-q", "-m", "base");
  change(repo);
  git("add", "-A");
  git("commit", "-q", "-m", "head");
  return git("diff", "HEAD~1", "HEAD");
}
const write = (repo: string, rel: string, content: string | Buffer) => {
  mkdirSync(dirname(join(repo, rel)), { recursive: true });
  writeFileSync(join(repo, rel), content);
};

const GUARD_FILE = "src/lib/guard.ts";
const GUARD_BASE = [
  "export function requireAdmin(user) {",
  "  if (!user) {",
  '    throw new Error("unauthenticated");',
  "  }",
  "  if (!user.isAdmin) {",
  '    throw new Error("forbidden");',
  "  }",
  "  return user;",
  "}",
  "",
].join("\n");
const GUARD_REMOVED = GUARD_BASE.split("\n")
  .filter((_l, i) => i < 4 || i > 6)
  .join("\n");
const thirty = Array.from({ length: 30 }, (_v, i) => `line ${i + 1}`);

const fixtures = {
  guardRemoval: realDiff({ [GUARD_FILE]: GUARD_BASE }, (repo) =>
    write(repo, GUARD_FILE, GUARD_REMOVED),
  ),
  deletion: realDiff({ "src/legacy.ts": "a\nb\nc\n" }, (repo) =>
    rmSync(join(repo, "src/legacy.ts")),
  ),
  mixed: realDiff({ "src/mixed.ts": thirty.join("\n") + "\n" }, (repo) => {
    const next = [...thirty];
    next[2] = "line three changed";
    next.splice(15, 0, "inserted A", "inserted B");
    next.splice(next.indexOf("line 27"), 1);
    write(repo, "src/mixed.ts", next.join("\n") + "\n");
  }),
  renameOnly: realDiff({ "src/a.ts": thirty.join("\n") + "\n" }, (repo) =>
    renameSync(join(repo, "src/a.ts"), join(repo, "src/b.ts")),
  ),
  renameEdit: realDiff({ "src/a.ts": thirty.join("\n") + "\n" }, (repo) => {
    renameSync(join(repo, "src/a.ts"), join(repo, "src/b.ts"));
    const next = [...thirty];
    next[9] = "line ten changed";
    write(repo, "src/b.ts", next.join("\n") + "\n");
  }),
  modeOnly: realDiff({ "bin/run.sh": "#!/bin/sh\necho ok\n" }, (repo) =>
    chmodSync(join(repo, "bin/run.sh"), 0o755),
  ),
  binaryAdd: realDiff({ "README.md": "x\n" }, (repo) =>
    write(repo, "img.bin", Buffer.from([0, 1, 2, 3, 0, 255, 254, 0])),
  ),
  newFile: realDiff({ "README.md": "x\n" }, (repo) =>
    write(repo, "src/new.ts", "one\ntwo\nthree\nfour\n"),
  ),
  noNewline: realDiff({ "notes.txt": "a\nb" }, (repo) => write(repo, "notes.txt", "a\nc")),
  combined: realDiff(
    { [GUARD_FILE]: GUARD_BASE, "src/legacy.ts": "a\nb\nc\n", "README.md": "x\n" },
    (repo) => {
      write(repo, GUARD_FILE, GUARD_REMOVED);
      rmSync(join(repo, "src/legacy.ts"));
      write(repo, "src/new.ts", "one\ntwo\n");
    },
  ),
};

const expectNoLeak = (r: Run) => {
  expect(r.out).not.toContain("SENTINEL");
  expect(r.out).not.toContain("http");
  for (const l of r.lines) expect(l).toMatch(LINE);
};
const hunkInvariants = (m: Manifest) => {
  let hunks = 0;
  let unsupported = 0;
  for (const f of m.files) {
    hunks += f.hunks.length;
    if (f.unsupported !== null) unsupported += 1;
    expect(f.unsupported === null).toBe(f.kind !== "unsupported");
    for (const h of f.hunks) {
      const oldLen = h.oldSpan ? h.oldSpan[1] - h.oldSpan[0] + 1 : 0;
      const newLen = h.newSpan ? h.newSpan[1] - h.newSpan[0] + 1 : 0;
      expect(oldLen).toBe(h.removed + h.context);
      expect(newLen).toBe(h.added + h.context);
    }
  }
  expect(m.hunkCount).toBe(hunks);
  expect(m.unsupported).toBe(unsupported);
};

describe("validator — attestation of a complete run", () => {
  it("attests a completed SDK run with zero denials, exact head, full file+hunk coverage and only p3 findings; prints enum lines and manifest-resolved identities only", () => {
    const r = runValidator({
      structured: reviewed([
        finding(),
        finding({ category: "test_gap", file: FILE_B, line: 9, confidence: 60 }),
      ]),
    });
    expect(r.code).toBe(0);
    expectNoLeak(r);
    expect(r.lines).toEqual([
      "review-result: v3",
      `expected_head: ${HEAD}`,
      "step: success",
      "manifest: ok",
      "changed_files: 2",
      "hunks: 2",
      "unsupported_changes: 0",
      "permission_denials: 0",
      "num_turns: 7",
      "sdk: completed",
      "structured: ok",
      "head: match",
      "outcome: reviewed",
      "files_inspected: 2",
      "hunks_inspected: 2",
      "coverage: full",
      "findings: 2",
      "finding: p3 bug file=0 side=new line=181 confidence=85",
      "finding: p3 test_gap file=1 side=new line=9 confidence=60",
      `changed_file: 0 modify ${FILE_A}`,
      `changed_file: 1 add ${FILE_B}`,
      "gate: passed",
      "verdict: attested",
    ]);
  });
  it("attests with zero findings and accepts an old-side finding on a removed line of a modified file", () => {
    const zero = runValidator({ structured: reviewed() });
    expect(zero.code).toBe(0);
    expect(zero.lines).toContain("verdict: attested");
    const old = runValidator({ structured: reviewed([finding({ side: "old", line: 175 })]) });
    expect(old.code).toBe(0);
    expect(old.lines).toContain("finding: p3 bug file=0 side=old line=175 confidence=85");
  });
});

describe("validator — gate (A4) and unsupported entries", () => {
  it.each([
    ["p1", 90, "blocked"],
    ["p2", 50, "blocked"],
    ["p1", 49, "manual_review"],
    ["p2", 0, "manual_review"],
  ])("%s at confidence %i -> %s, exit 1", (severity, confidence, expected) => {
    const r = runValidator({
      structured: reviewed([finding({ severity, category: "security", confidence })]),
    });
    expect(r.code).toBe(1);
    expect(r.lines).toContain(`gate: ${expected}`);
    expect(r.lines).toContain(`verdict: ${expected}`);
  });
  it("a blocking finding together with an invalid input yields verdict failed, not blocked", () => {
    const r = runValidator({
      structured: reviewed([finding({ severity: "p1", confidence: 90 })], { filesInspected: 1 }),
    });
    expect(r.code).toBe(1);
    expect(r.lines).toContain("coverage: partial");
    expect(r.lines).toContain("gate: blocked");
    expect(r.lines).toContain("verdict: failed");
  });
  it("an unsupported change entry (binary / rename-only / mode-only) forces manual review even with a clean result; a p1 still blocks", () => {
    const m = withUnsupported(DEFAULT_MANIFEST, "binary");
    const clean = runValidator({ manifest: m, structured: reviewed([], { filesInspected: 3 }) });
    expect(clean.code).toBe(1);
    expect(clean.lines).toContain("unsupported_changes: 1");
    expect(clean.lines).toContain("unsupported_change: 2 binary");
    expect(clean.lines).toContain("coverage: full");
    expect(clean.lines).toContain("gate: manual_review");
    expect(clean.lines).toContain("verdict: manual_review");
    const p1 = runValidator({
      manifest: m,
      structured: reviewed([finding({ severity: "p1", confidence: 95 })], { filesInspected: 3 }),
    });
    expect(p1.lines).toContain("gate: blocked");
    expect(p1.lines).toContain("verdict: blocked");
  });
});

describe("validator — null and non-object representations (A1) never attest", () => {
  const withoutStructured = completed(undefined).map((m) => {
    if (m.type !== "result") return m;
    const copy: Record<string, unknown> = { ...m };
    delete copy.structured_output;
    return copy;
  });
  const entry0 = DEFAULT_MANIFEST.files[0];
  it.each([
    ["null structured_output", { structured: null }, "structured: invalid_shape"],
    ["numeric structured_output", { structured: 1 }, "structured: invalid_shape"],
    ["string structured_output", { structured: SENTINELS[3] }, "structured: invalid_shape"],
    ["array structured_output", { structured: [reviewed()] }, "structured: invalid_shape"],
    ["missing structured_output", { execution: withoutStructured }, "structured: missing"],
    ["null execution file", { executionRaw: "null" }, "execution_file: invalid_shape"],
    ["numeric execution file", { executionRaw: "1" }, "execution_file: invalid_shape"],
    [
      "object execution file",
      { executionRaw: JSON.stringify({ secret: SENTINELS[0] }) },
      "execution_file: invalid_shape",
    ],
    [
      "malformed execution file",
      { executionRaw: "{not json " + SENTINELS[0] },
      "execution_file: malformed",
    ],
    ["missing execution file", { omitExecution: true }, "execution_file: missing"],
    ["no result message", { execution: [{ type: "system", subtype: "init" }] }, "sdk: no_result"],
    ["null manifest", { manifestRaw: "null" }, "manifest: invalid"],
    ["array manifest", { manifestRaw: "[]" }, "manifest: invalid"],
    ["malformed manifest", { manifestRaw: "{" + SENTINELS[1] }, "manifest: malformed"],
    ["missing manifest", { omitManifest: true }, "manifest: missing"],
    [
      "empty manifest",
      { manifest: { ...DEFAULT_MANIFEST, files: [], hunkCount: 0 } },
      "manifest: empty",
    ],
    [
      "stale manifest head",
      { manifest: { ...DEFAULT_MANIFEST, head: OTHER } },
      "manifest: stale_head",
    ],
    [
      "manifest with extra key",
      { manifest: { ...DEFAULT_MANIFEST, note: SENTINELS[3] } },
      "manifest: invalid",
    ],
    [
      "manifest hunkCount mismatch",
      { manifest: { ...DEFAULT_MANIFEST, hunkCount: 3 } },
      "manifest: invalid",
    ],
    [
      "manifest unsupported count mismatch",
      { manifest: { ...DEFAULT_MANIFEST, unsupported: 1 } },
      "manifest: invalid",
    ],
    [
      "manifest kind/unsupported inconsistency",
      {
        manifest: {
          ...DEFAULT_MANIFEST,
          files: [{ ...entry0, unsupported: "binary" }, DEFAULT_MANIFEST.files[1]],
          unsupported: 1,
        },
      },
      "manifest: invalid",
    ],
    [
      "manifest with bad span",
      {
        manifest: {
          ...DEFAULT_MANIFEST,
          files: [
            { ...entry0, hunks: [{ ...entry0.hunks[0], newSpan: [5, 4] }] },
            DEFAULT_MANIFEST.files[1],
          ],
        },
      },
      "manifest: invalid",
    ],
    [
      "manifest with unsafe path",
      {
        manifest: {
          ...DEFAULT_MANIFEST,
          files: [{ ...entry0, newPath: "../x.ts" }, DEFAULT_MANIFEST.files[1]],
        },
      },
      "manifest: invalid",
    ],
    [
      "manifest with bad base",
      { manifest: { ...DEFAULT_MANIFEST, base: "main" } },
      "manifest: invalid",
    ],
  ])("%s -> %s", (_name, opts, expectedLine) => {
    const r = runValidator({ structured: reviewed(), ...(opts as RunOptions) });
    expect(r.code).toBe(1);
    expect(r.lines).toContain(expectedLine);
    expect(r.lines).toContain("verdict: failed");
    expectNoLeak(r);
  });
});

describe("validator — SDK completion and refusals", () => {
  it("fails on refused tools, errored results, invalid denial accounting; never echoes denial content", () => {
    const denied = runValidator({
      execution: completed(reviewed(), [
        { tool_name: "Bash", tool_input: { command: SENTINELS[2] } },
        { tool_name: "WebFetch", tool_input: { url: SENTINELS[1] } },
      ]),
    });
    expect(denied.code).toBe(1);
    expect(denied.lines).toContain("permission_denials: 2");
    expect(denied.lines).toContain("sdk: refused_tools");
    expectNoLeak(denied);
    const errored = runValidator({ execution: completed(reviewed(), [], { is_error: true }) });
    expect(errored.code).toBe(1);
    expect(errored.lines).toContain("sdk: failed");
    const wrongSubtype = runValidator({
      execution: completed(reviewed(), [], { subtype: "error_max_turns" }),
    });
    expect(wrongSubtype.lines).toContain("sdk: failed");
    const hostile = runValidator({
      execution: [
        null,
        1,
        "s",
        {
          type: "result",
          subtype: "success",
          is_error: false,
          permission_denials: "x",
          num_turns: -1,
          structured_output: reviewed(),
          result: SENTINELS[0],
        },
      ],
    });
    expect(hostile.code).toBe(1);
    expect(hostile.lines).toContain("permission_denials: -1");
    expect(hostile.lines).toContain("sdk: invalid");
    expectNoLeak(hostile);
  });
  it("fails when the review step did not succeed, even with a valid-looking result", () => {
    const failed = runValidator({ structured: reviewed(), stepOutcome: "failure" });
    expect(failed.code).toBe(1);
    expect(failed.lines).toContain("step: failure");
    const skipped = runValidator({ omitExecution: true, stepOutcome: "skipped" });
    expect(skipped.code).toBe(1);
    expect(skipped.lines).toContain("step: skipped");
    expect(skipped.lines).toContain("execution_file: missing");
    expect(skipped.lines).toContain("verdict: failed");
  });
});

describe("validator — head, outcome, coverage", () => {
  it("fails on stale, invalid or empty expected head and on incomplete or invalid outcome", () => {
    const stale = runValidator({ structured: reviewed([], { reviewedHeadSha: OTHER }) });
    expect(stale.code).toBe(1);
    expect(stale.lines).toContain("head: mismatch");
    const invalidHead = runValidator({
      structured: reviewed([], { reviewedHeadSha: "HEAD~1; rm -rf /" }),
    });
    expect(invalidHead.lines).toContain("head: invalid");
    expect(invalidHead.out).not.toContain("rm -rf");
    const incomplete = runValidator({
      structured: reviewed([], { outcome: "incomplete", filesInspected: 0, hunksInspected: 0 }),
    });
    expect(incomplete.code).toBe(1);
    expect(incomplete.lines).toContain("outcome: incomplete");
    const badOutcome = runValidator({ structured: reviewed([], { outcome: SENTINELS[3] }) });
    expect(badOutcome.lines).toContain("outcome: invalid");
    expectNoLeak(badOutcome);
    const badExpected = runValidator({ structured: reviewed(), expected: "" });
    expect(badExpected.code).toBe(1);
    expect(badExpected.lines).toContain("expected_head: invalid");
  });
  it("requires filesInspected and hunksInspected to equal the manifest counts (A2/B1)", () => {
    const none = runValidator({ structured: reviewed([], { filesInspected: 0 }) });
    expect(none.code).toBe(1);
    expect(none.lines).toContain("coverage: none");
    expect(runValidator({ structured: reviewed([], { filesInspected: 1 }) }).lines).toContain(
      "coverage: partial",
    );
    expect(runValidator({ structured: reviewed([], { filesInspected: 3 }) }).lines).toContain(
      "coverage: excess",
    );
    expect(runValidator({ structured: reviewed([], { hunksInspected: 1 }) }).lines).toContain(
      "coverage: hunks_mismatch",
    );
    expect(runValidator({ structured: reviewed([], { hunksInspected: 0 }) }).lines).toContain(
      "coverage: hunks_mismatch",
    );
    expect(runValidator({ structured: reviewed([], { filesInspected: "2" }) }).lines).toContain(
      "coverage: invalid",
    );
    const legacyShape = runValidator({
      structured: { reviewedHeadSha: HEAD, outcome: "reviewed", filesInspected: 2, findings: [] },
    });
    expect(legacyShape.lines).toContain("structured: invalid_shape");
  });
});

describe("validator — findings resolved only against the trusted manifest (A2)", () => {
  it.each([
    ["alphabet-only secret-like name", { file: SENTINELS[0] }, "finding: unlisted_file"],
    ["alphabet-only prose name", { file: "PROSE_SENTINEL_TEXT.ts" }, "finding: unlisted_file"],
    ["real repo file not in the diff", { file: "src/lib/store.ts" }, "finding: unlisted_file"],
    ["case variant of a listed file", { file: FILE_A.toUpperCase() }, "finding: unlisted_file"],
    [
      "old side of an added file (no old path)",
      { file: FILE_B, side: "old", line: 3 },
      "finding: unlisted_file",
    ],
    ["new-side line before the hunk span", { line: 169 }, "finding: outside_hunks"],
    ["new-side line just past the hunk span", { line: 201 }, "finding: outside_hunks"],
    ["old-side line past the old span", { side: "old", line: 181 }, "finding: outside_hunks"],
    ["URL as file", { file: SENTINELS[1] }, "finding: unlisted_file"],
    ["traversal", { file: "../../etc/passwd" }, "finding: unlisted_file"],
    ["absolute path", { file: "/absolute/path.ts" }, "finding: unlisted_file"],
    ["unknown category", { category: "prose" }, "finding: invalid"],
    ["unknown severity", { severity: "critical" }, "finding: invalid"],
    ["unknown side", { side: "both" }, "finding: invalid"],
    ["missing side", { side: undefined }, "finding: invalid"],
    ["line 0", { line: 0 }, "finding: invalid"],
    ["string line", { line: "181" }, "finding: invalid"],
    ["confidence 101", { confidence: 101 }, "finding: invalid"],
    ["extra message key", { message: SENTINELS[3] }, "finding: invalid"],
    ["extra url key", { url: SENTINELS[1] }, "finding: invalid"],
    ["non-string file", { file: 3 }, "finding: invalid"],
  ])("%s -> %s and nothing model-chosen is printed", (_name, over, expectedLine) => {
    const f: Record<string, unknown> = finding(over as Record<string, unknown>);
    for (const k of Object.keys(f)) if (f[k] === undefined) delete f[k];
    const r = runValidator({ structured: reviewed([f]) });
    expect(r.code).toBe(1);
    expect(r.lines).toContain(expectedLine);
    expect(r.lines).toContain("verdict: failed");
    expect(r.out).not.toContain("PROSE");
    expect(r.out).not.toContain("passwd");
    expect(r.out).not.toContain("absolute");
    expect(r.out).not.toContain("store.ts");
    expectNoLeak(r);
  });
  it("an unsupported entry cannot be referenced even when its paths are known", () => {
    const m: Manifest = {
      ...DEFAULT_MANIFEST,
      files: [
        {
          kind: "unsupported",
          oldPath: "src/x.ts",
          newPath: "src/y.ts",
          hunks: [],
          unsupported: "rename_only",
        },
        DEFAULT_MANIFEST.files[1],
      ],
      hunkCount: 1,
      unsupported: 1,
    };
    const r = runValidator({
      manifest: m,
      structured: reviewed([finding({ file: "src/y.ts", line: 1 })], { hunksInspected: 1 }),
    });
    expect(r.lines).toContain("finding: unlisted_file");
  });
  it("refuses more than 20 findings or a non-array, and marks findings unresolvable when the manifest failed", () => {
    const tooMany = runValidator({
      structured: reviewed(Array.from({ length: 21 }, () => finding())),
    });
    expect(tooMany.code).toBe(1);
    expect(tooMany.lines).toContain("findings: invalid");
    expect(runValidator({ structured: reviewed([], { findings: "none" }) }).lines).toContain(
      "findings: invalid",
    );
    const noManifest = runValidator({ structured: reviewed([finding()]), omitManifest: true });
    expect(noManifest.lines).toContain("findings: unresolvable");
    expect(noManifest.out).not.toContain("finding: p3");
  });
  it("fails on oversized or extra-key structured output", () => {
    const big = runValidator({ structured: reviewed([], { pad: "x".repeat(25000) }) });
    expect(big.code).toBe(1);
    expect(big.lines).toContain("structured: too_large");
    const extraKey = runValidator({ structured: { ...reviewed(), note: SENTINELS[3] } });
    expect(extraKey.lines).toContain("structured: invalid_shape");
    expectNoLeak(extraKey);
  });
});

describe("manifest collector — real git diffs (B1/B2)", () => {
  it("removal-only change (authorization guard deleted): one hunk, removed lines addressable on the old side, context on the new side", () => {
    const r = runManifest(fixtures.guardRemoval);
    expect(r.code).toBe(0);
    expect(r.lines).toEqual([
      "manifest: written",
      "changed_files: 1",
      "hunks: 1",
      "unsupported_changes: 0",
      `head: ${HEAD}`,
      `base: ${BASE}`,
    ]);
    const m = r.manifest!;
    hunkInvariants(m);
    expect(m.files).toEqual([
      {
        kind: "modify",
        oldPath: GUARD_FILE,
        newPath: GUARD_FILE,
        hunks: [{ oldSpan: [2, 9], newSpan: [2, 6], added: 0, removed: 3, context: 5 }],
        unsupported: null,
      },
    ]);
    const base = (findings: unknown[]) =>
      runValidator({
        manifest: m,
        structured: reviewed(findings, { filesInspected: 1, hunksInspected: 1 }),
      });
    const removedGuard = base([
      finding({
        file: GUARD_FILE,
        side: "old",
        line: 5,
        category: "permission",
        severity: "p2",
        confidence: 90,
      }),
    ]);
    expect(removedGuard.code).toBe(1);
    expect(removedGuard.lines).toContain(
      "finding: p2 permission file=0 side=old line=5 confidence=90",
    );
    expect(removedGuard.lines).toContain(`changed_file: 0 modify ${GUARD_FILE}`);
    expect(removedGuard.lines).toContain("verdict: blocked");
    const contextNew = base([finding({ file: GUARD_FILE, side: "new", line: 3 })]);
    expect(contextNew.code).toBe(0);
    expect(contextNew.lines).toContain("finding: p3 bug file=0 side=new line=3 confidence=85");
    const outsideOld = base([finding({ file: GUARD_FILE, side: "old", line: 1 })]);
    expect(outsideOld.lines).toContain("finding: outside_hunks");
    const outsideNew = base([finding({ file: GUARD_FILE, side: "new", line: 7 })]);
    expect(outsideNew.lines).toContain("finding: outside_hunks");
    // Honest limit: a zero-finding result that claims full file+hunk coverage attests; the model's claim, not proof.
    const zero = base([]);
    expect(zero.code).toBe(0);
    expect(zero.lines).toContain("coverage: full");
  });
  it("whole-file deletion: kind delete, old path only, every old line addressable, new side unlisted", () => {
    const m = runManifest(fixtures.deletion).manifest!;
    hunkInvariants(m);
    expect(m.files).toEqual([
      {
        kind: "delete",
        oldPath: "src/legacy.ts",
        newPath: null,
        hunks: [{ oldSpan: [1, 3], newSpan: null, added: 0, removed: 3, context: 0 }],
        unsupported: null,
      },
    ]);
    const base = (findings: unknown[]) =>
      runValidator({
        manifest: m,
        structured: reviewed(findings, { filesInspected: 1, hunksInspected: 1 }),
      });
    const old = base([finding({ file: "src/legacy.ts", side: "old", line: 2 })]);
    expect(old.code).toBe(0);
    expect(old.lines).toContain("changed_file: 0 delete src/legacy.ts");
    expect(base([finding({ file: "src/legacy.ts", side: "new", line: 2 })]).lines).toContain(
      "finding: unlisted_file",
    );
    expect(base([finding({ file: "src/legacy.ts", side: "old", line: 4 })]).lines).toContain(
      "finding: outside_hunks",
    );
  });
  it("mixed add/remove/context: every hunk body consumed against its header, spans consistent", () => {
    const m = runManifest(fixtures.mixed).manifest!;
    hunkInvariants(m);
    expect(m.files).toHaveLength(1);
    expect(m.files[0].kind).toBe("modify");
    const hunks = m.files[0].hunks;
    expect(hunks.length).toBeGreaterThanOrEqual(2);
    expect(hunks.reduce((n, h) => n + h.added, 0)).toBe(3);
    expect(hunks.reduce((n, h) => n + h.removed, 0)).toBe(2);
    expect(hunks[0].oldSpan![0]).toBe(1);
    for (let i = 1; i < hunks.length; i++)
      expect(hunks[i].oldSpan![0]).toBeGreaterThan(hunks[i - 1].oldSpan![1]);
  });
  it("rename without content change -> unsupported rename_only -> manual review; rename with edit is addressable on both paths", () => {
    const only = runManifest(fixtures.renameOnly).manifest!;
    hunkInvariants(only);
    expect(only.files).toEqual([
      { kind: "unsupported", oldPath: null, newPath: null, hunks: [], unsupported: "rename_only" },
    ]);
    const r = runValidator({
      manifest: only,
      structured: reviewed([], { filesInspected: 1, hunksInspected: 0 }),
    });
    expect(r.code).toBe(1);
    expect(r.lines).toContain("unsupported_change: 0 rename_only");
    expect(r.lines).toContain("verdict: manual_review");
    const edit = runManifest(fixtures.renameEdit).manifest!;
    hunkInvariants(edit);
    expect(edit.files).toHaveLength(1);
    expect(edit.files[0]).toMatchObject({
      kind: "rename",
      oldPath: "src/a.ts",
      newPath: "src/b.ts",
      unsupported: null,
    });
    expect(edit.files[0].hunks).toHaveLength(1);
    const base = (findings: unknown[]) =>
      runValidator({
        manifest: edit,
        structured: reviewed(findings, { filesInspected: 1, hunksInspected: 1 }),
      });
    const oldSide = base([finding({ file: "src/a.ts", side: "old", line: 10 })]);
    expect(oldSide.code).toBe(0);
    expect(oldSide.lines).toContain("changed_file: 0 rename src/a.ts src/b.ts");
    expect(base([finding({ file: "src/b.ts", side: "new", line: 10 })]).code).toBe(0);
    expect(base([finding({ file: "src/a.ts", side: "new", line: 10 })]).lines).toContain(
      "finding: unlisted_file",
    );
    expect(base([finding({ file: "src/b.ts", side: "old", line: 10 })]).lines).toContain(
      "finding: unlisted_file",
    );
  });
  it("mode-only change and binary file -> unsupported -> manual review, never attested", () => {
    const mode = runManifest(fixtures.modeOnly).manifest!;
    expect(mode.files).toEqual([
      { kind: "unsupported", oldPath: null, newPath: null, hunks: [], unsupported: "mode_only" },
    ]);
    const modeRun = runValidator({
      manifest: mode,
      structured: reviewed([], { filesInspected: 1, hunksInspected: 0 }),
    });
    expect(modeRun.code).toBe(1);
    expect(modeRun.lines).toContain("verdict: manual_review");
    const bin = runManifest(fixtures.binaryAdd).manifest!;
    expect(bin.files).toEqual([
      { kind: "unsupported", oldPath: null, newPath: null, hunks: [], unsupported: "binary" },
    ]);
    const binRun = runValidator({
      manifest: bin,
      structured: reviewed([], { filesInspected: 1, hunksInspected: 0 }),
    });
    expect(binRun.code).toBe(1);
    expect(binRun.lines).toContain("unsupported_change: 0 binary");
    expect(binRun.lines).toContain("verdict: manual_review");
  });
  it("new file, missing-trailing-newline markers and a combined multi-file commit parse correctly", () => {
    const added = runManifest(fixtures.newFile).manifest!;
    hunkInvariants(added);
    expect(added.files).toEqual([
      {
        kind: "add",
        oldPath: null,
        newPath: "src/new.ts",
        hunks: [{ oldSpan: null, newSpan: [1, 4], added: 4, removed: 0, context: 0 }],
        unsupported: null,
      },
    ]);
    const nn = runManifest(fixtures.noNewline);
    expect(nn.code).toBe(0);
    hunkInvariants(nn.manifest!);
    expect(nn.manifest!.files[0].hunks).toEqual([
      { oldSpan: [1, 2], newSpan: [1, 2], added: 1, removed: 1, context: 1 },
    ]);
    const combined = runManifest(fixtures.combined);
    expect(combined.code).toBe(0);
    const c = combined.manifest!;
    hunkInvariants(c);
    expect(c.files.map((f) => [f.kind, f.oldPath, f.newPath])).toEqual([
      ["delete", "src/legacy.ts", null],
      ["modify", GUARD_FILE, GUARD_FILE],
      ["add", null, "src/new.ts"],
    ]);
    expect(c.hunkCount).toBe(3);
    expect(combined.lines).toContain("changed_files: 3");
    expect(combined.lines).toContain("hunks: 3");
    const attested = runValidator({
      manifest: c,
      structured: reviewed([], { filesInspected: 3, hunksInspected: 3 }),
    });
    expect(attested.code).toBe(0);
    expect(
      runValidator({
        manifest: c,
        structured: reviewed([], { filesInspected: 3, hunksInspected: 2 }),
      }).lines,
    ).toContain("coverage: hunks_mismatch");
  });
  it("fails closed on malformed diffs, identity problems, empty and oversized input", () => {
    const g = fixtures.guardRemoval.split("\n");
    const truncated = g.slice(0, -2).join("\n") + "\n";
    expect(runManifest(truncated).lines).toContain("manifest: malformed_diff");
    const extraPlus = fixtures.guardRemoval.replace(/(@@[^\n]*\n)/, "$1+injected line\n");
    expect(runManifest(extraPlus).lines).toContain("manifest: malformed_diff");
    const badHeader = fixtures.guardRemoval.replace("@@ -2,8 +2,5 @@", "@@ -2,8 +2,X @@");
    expect(runManifest(badHeader).lines).toContain("manifest: malformed_diff");
    const preamble = "PROSE_SENTINEL_TEXT\n" + fixtures.guardRemoval;
    const pre = runManifest(preamble);
    expect(pre.lines).toContain("manifest: malformed_diff");
    expect(pre.out).not.toContain("SENTINEL");
    for (const r of [runManifest(truncated), runManifest(extraPlus), runManifest(badHeader)]) {
      expect(r.code).toBe(1);
      expect(r.manifest).toBeNull();
    }
    expect(runManifest(fixtures.guardRemoval, "not-a-sha").lines).toContain(
      "manifest: invalid_identity",
    );
    expect(runManifest(fixtures.guardRemoval, HEAD, HEAD).lines).toContain(
      "manifest: invalid_identity",
    );
    expect(runManifest("").lines).toContain("manifest: empty");
    const big = runManifest("x".repeat(20 * 1024 * 1024 + 1));
    expect(big.code).toBe(1);
    expect(big.lines).toContain("manifest: too_large");
    expect(big.manifest).toBeNull();
  });
});

describe("workflow transport boundary (A3) and configuration", () => {
  type Step = {
    name?: string;
    uses?: string;
    run?: string;
    if?: string;
    env?: Record<string, string>;
    with?: Record<string, unknown>;
  };
  const doc = yaml.load(workflow) as {
    jobs: { "claude-review": { permissions: Record<string, string>; steps: Step[] } };
  };
  const job = doc.jobs["claude-review"];
  const steps = job.steps;
  const action = steps.find((s) => s.uses?.startsWith("anthropics/claude-code-action@v1"))!;
  const validator = steps.find((s) => s.run?.includes("CI_REVIEW_VALIDATOR"))!;
  const manifest = steps.find((s) => s.run?.includes("CI_REVIEW_MANIFEST"))!;
  it("no step env, with or run references an action output; env carries trusted values only", () => {
    expect(workflow).not.toContain("steps.claude-review.outputs");
    expect(workflow).not.toContain("structured_output }}");
    expect(Object.keys(validator.env ?? {}).sort()).toEqual([
      "EXPECTED_HEAD_SHA",
      "REVIEW_STEP_OUTCOME",
      "RUNNER_TEMP_DIR",
    ]);
    expect(validator.env!.REVIEW_STEP_OUTCOME).toBe("${{ steps.claude-review.outcome }}");
    expect(validator.env!.EXPECTED_HEAD_SHA).toBe("${{ github.event.pull_request.head.sha }}");
    expect(validator.if).toBe("always()");
    expect(Object.keys(manifest.env ?? {}).sort()).toEqual([
      "BASE_SHA",
      "GH_TOKEN",
      "HEAD_SHA",
      "RUNNER_TEMP_DIR",
    ]);
    expect(manifest.env!.HEAD_SHA).toBe("${{ github.event.pull_request.head.sha }}");
    expect(manifest.env!.BASE_SHA).toBe("${{ github.event.pull_request.base.sha }}");
    expect(manifest.run).toContain('compare/$BASE_SHA...$HEAD_SHA"');
    expect(manifest.run).not.toContain("gh pr ");
    for (const s of [validator, manifest]) expect(s.run).not.toContain("${{");
  });
  it("the action step has no plugin, report or full-output inputs; the prompt needs no commands; permissions unchanged", () => {
    expect(Object.keys(action.with!).sort()).toEqual([
      "claude_args",
      "claude_code_oauth_token",
      "prompt",
    ]);
    expect(action.with!.prompt as string).not.toMatch(/\bgh\b/);
    expect(action.with!.prompt as string).toContain(".ci-review/pr.diff");
    expect(workflow).not.toMatch(
      /^\s*(display_report|show_full_output|plugins|plugin_marketplaces|github_token|additional_permissions):/m,
    );
    expect(job.permissions).toEqual({
      contents: "read",
      "pull-requests": "read",
      issues: "read",
      "id-token": "write",
    });
    expect(steps.map((s) => s.uses ?? s.name)).toEqual([
      "actions/checkout@v4",
      "Remove in-repository Claude configuration from the runner checkout",
      "Collect trusted PR manifest (immutable compare diff, hunk spans, unsupported entries)",
      "anthropics/claude-code-action@v1",
      "Validate review result (fail-closed, enums only)",
    ]);
    expect(steps[0].with).toEqual({ "fetch-depth": 1, "persist-credentials": false });
    expect(steps[1].run!.trim()).toBe("rm -rf -- .claude .mcp.json");
  });
  it("claude_args parse exactly as intended by the action's v1 shell-quote parser (reproduced locally): Read/Grep/Glob only, no Bash", () => {
    // Mirrors anthropics/claude-code-action v1 base-action/src/parse-sdk-options.ts (fetched 27 September 2026):
    // comment-line stripping, shell metachar escaping, shell-quote parse, glob-pattern round-trip, accumulating flags.
    const META = new Map<string, string>([
      ["(", ""],
      [")", ""],
      ["|", ""],
      ["&", ""],
      [";", ""],
      ["<", ""],
      [">", ""],
    ]);
    const UNMETA = new Map([...META].map(([k, v]) => [v, k]));
    const esc = (s: string) => s.replace(/[()|&;<>]/g, (c) => META.get(c)!);
    const unesc = (s: string) => s.replace(/[-]/g, (c) => UNMETA.get(c)!);
    const ACCUMULATING = new Set([
      "allowedTools",
      "allowed-tools",
      "disallowedTools",
      "disallowed-tools",
      "mcp-config",
      "add-dir",
    ]);
    const parse = (claudeArgs: string) => {
      const stripped = claudeArgs
        .split("\n")
        .filter((l) => !l.trim().startsWith("#"))
        .join("\n");
      const args = shellQuote
        .parse(esc(stripped))
        .map((a) =>
          typeof a === "string"
            ? unesc(a)
            : typeof a === "object" && a !== null && "pattern" in a
              ? unesc((a as { pattern: string }).pattern)
              : undefined,
        )
        .filter((a): a is string => typeof a === "string");
      const result: Record<string, string | null> = {};
      for (let i = 0; i < args.length; i++) {
        const arg = args[i];
        if (!arg.startsWith("--")) continue;
        const flag = arg.slice(2);
        const next = args[i + 1];
        if (next && !next.startsWith("--")) {
          if (ACCUMULATING.has(flag)) {
            const values: string[] = [];
            while (i + 1 < args.length && !args[i + 1].startsWith("--")) {
              i++;
              values.push(args[i]);
            }
            result[flag] = values.join("\x00");
          } else {
            result[flag] = next;
            i++;
          }
        } else result[flag] = null;
      }
      return result;
    };
    const claudeArgs = action.with!.claude_args as string;
    expect(claudeArgs).not.toContain("\n");
    expect(claudeArgs).not.toContain("Bash(");
    const parsed = parse(claudeArgs);
    expect(Object.keys(parsed).sort()).toEqual([
      "allowed-tools",
      "disallowed-tools",
      "json-schema",
      "max-turns",
      "setting-sources",
      "strict-mcp-config",
      "tools",
    ]);
    expect(parsed["tools"]).toBe("Read,Grep,Glob");
    expect(parsed["allowed-tools"]!.split(",")).toEqual(["Read", "Grep", "Glob"]);
    expect(parsed["disallowed-tools"]!.split(",")).toEqual([
      "Bash",
      "Task",
      "Agent",
      "Edit",
      "Write",
      "MultiEdit",
      "NotebookEdit",
      "WebFetch",
      "WebSearch",
      "TodoWrite",
      "Skill",
    ]);
    expect(parsed["max-turns"]).toBe("30");
    expect(parsed["setting-sources"]).toBe("user");
    expect(parsed["strict-mcp-config"]).toBeNull();
    const schema = JSON.parse(parsed["json-schema"]!) as {
      additionalProperties: boolean;
      required: string[];
      properties: Record<
        string,
        {
          pattern?: string;
          enum?: string[];
          items?: { required: string[]; properties: Record<string, { enum?: string[] }> };
        }
      >;
    };
    expect(schema.additionalProperties).toBe(false);
    expect(schema.required).toEqual([
      "reviewedHeadSha",
      "outcome",
      "filesInspected",
      "hunksInspected",
      "findings",
    ]);
    expect(schema.properties.reviewedHeadSha.pattern).toBe("^[0-9a-f]{40}$");
    expect(schema.properties.outcome.enum).toEqual(["reviewed", "incomplete"]);
    expect(schema.properties.findings.items!.required).toEqual([
      "category",
      "severity",
      "file",
      "side",
      "line",
      "confidence",
    ]);
    expect(schema.properties.findings.items!.properties.side.enum).toEqual(["new", "old"]);
  });
});
