/**
 * Baseline security headers for every worker-served response (SSR HTML, API
 * routes, and server-routed files like /milo-analytics.js).
 *
 * Delivery mechanism (investigated 2026-08-19):
 * - Static assets under .output/public are served by Lovable's CDN layer,
 *   which honors the build-emitted `_headers` file (the `/assets/*`
 *   cache-control rule from it is visible on prod). That file is GENERATED by
 *   nitro at build time, so we don't hand-maintain a copy — and static assets
 *   aren't documents, so CSP/frame protection is meaningless for them anyway.
 * - Lovable's edge already injects strict-transport-security,
 *   x-content-type-options and referrer-policy on every response. We set them
 *   here too (same values) so the app doesn't silently lose them if that edge
 *   behavior ever changes; a duplicate identical header is harmless.
 * - Every HTML document and API response flows through the src/server.ts
 *   fetch wrapper, which is therefore the one reliable app-controlled hook.
 *   src/server.ts only applies these on production builds — the vite dev
 *   server's HMR websocket and inline helpers don't need to fight a CSP.
 */

const BASELINE_HEADERS: ReadonlyArray<readonly [string, string]> = [
  // Matches what Lovable's edge sends today. No `preload` — submitting to the
  // browser preload list is close to irreversible and is an owner decision.
  ["strict-transport-security", "max-age=31536000; includeSubDomains"],
  ["x-content-type-options", "nosniff"],
  ["referrer-policy", "strict-origin-when-cross-origin"],
  // The app has no legitimate embedding; frame-ancestors 'none' in the CSP is
  // the modern equivalent, X-Frame-Options covers pre-CSP2 user agents.
  ["x-frame-options", "DENY"],
  // Features the app never uses on any page.
  ["permissions-policy", "camera=(), microphone=(), geolocation=()"],
];

/**
 * Content-Security-Policy, applied to HTML documents only (API JSON and the
 * analytics script gain nothing from a CSP and it bloats every response).
 *
 * Documented exceptions — keep this list justified:
 * - script-src 'unsafe-inline': TanStack Start hydration is bootstrapped by
 *   inline scripts with no nonce infrastructure; removing this breaks
 *   hydration on every page. Revisit if Start ever grows CSP-nonce support.
 * - script-src cdn.paddle.com + frame-src buy.paddle.com/sandbox-buy +
 *   connect-src *.paddle.com: checkout today is a server-created hosted
 *   checkout URL (billing.functions.ts) so nothing Paddle loads on our pages
 *   yet, but the owner's checkout smoke test is pending and Paddle's overlay
 *   checkout needs exactly these — pre-allowed so a checkout iteration can't
 *   be silently broken by CSP.
 * - style-src 'unsafe-inline' + fonts.googleapis.com: Google Fonts CSS
 *   (Fraunces/Inter in __root.tsx) plus React inline style attributes.
 * - font-src fonts.gstatic.com: the font files the Google CSS points at.
 * - img-src https: data: blob:: article/editor previews render user-supplied
 *   images from arbitrary customer sites, plus Supabase storage and OAuth
 *   avatar hosts; enumerating them is not possible.
 * - connect-src *.supabase.co (https+wss): Lovable Cloud DB/auth/storage/edge
 *   functions; wildcard so a project change doesn't break prod.
 * - frame-ancestors 'none': no legitimate embedding (pairs with XFO DENY).
 */
export const CONTENT_SECURITY_POLICY = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "script-src 'self' 'unsafe-inline' https://cdn.paddle.com",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' data: https://fonts.gstatic.com",
  "img-src 'self' data: blob: https:",
  "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.paddle.com",
  "frame-src 'self' https://buy.paddle.com https://sandbox-buy.paddle.com",
  "worker-src 'self' blob:",
].join("; ");

/**
 * Returns a response carrying the baseline security headers. Headers already
 * set by a route win — this only fills in what's absent. Pure with respect to
 * the input response so routes/tests can rely on their own headers.
 */
export function withSecurityHeaders(response: Response): Response {
  // 101/websocket upgrades must pass through untouched (none served today).
  if (response.status === 101) return response;

  const headers = new Headers(response.headers);
  for (const [name, value] of BASELINE_HEADERS) {
    if (!headers.has(name)) headers.set(name, value);
  }
  const contentType = headers.get("content-type") ?? "";
  if (contentType.includes("text/html") && !headers.has("content-security-policy")) {
    headers.set("content-security-policy", CONTENT_SECURITY_POLICY);
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
