import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, LegalSection } from "@/components/LegalPage";

export const Route = createFileRoute("/ai-disclaimer")({
  head: () => ({
    meta: [
      { title: "AI Content Disclaimer — Milo Growth" },
      {
        name: "description",
        content: "How Milo uses AI-assisted generation and your responsibilities when publishing.",
      },
    ],
  }),
  component: AiDisclaimerPage,
});

function AiDisclaimerPage() {
  return (
    <LegalPage
      title="AI Content Disclaimer"
      intro="Milo uses AI to help you work faster — but AI output is a starting point, not a finished, verified result. Please read this before publishing AI-assisted content."
    >
      <LegalSection heading="Milo uses AI-assisted generation">
        <p>
          Milo uses AI-assisted generation to produce drafts, opportunities, audits and analyses
          based on the information you provide. These outputs are generated by automated models.
        </p>
      </LegalSection>

      <LegalSection heading="Outputs may need review">
        <p>
          AI outputs may be incomplete, inaccurate or unsuitable without review. Always review
          generated content before using or publishing it.
        </p>
      </LegalSection>

      <LegalSection heading="Auto-publish is optional and user-controlled">
        <p>
          Publishing to your website is something you control. Auto-publish is optional and only
          publishes content you have approved. Enable it only when you are comfortable publishing
          approved content automatically, and remember you remain responsible for reviewing content
          and claims before publishing.
        </p>
      </LegalSection>

      <LegalSection heading="Not professional advice">
        <p>
          Milo does not provide legal, medical, financial or other professional advice. Content that
          touches regulated topics, prices, health, finance or legal matters should be reviewed by a
          qualified professional before publishing.
        </p>
      </LegalSection>

      <LegalSection heading="No ranking or visibility guarantees">
        <p>
          Milo does not guarantee search rankings, traffic, conversions or revenue, and does not
          guarantee visibility or citation in AI tools. AI / search readiness features are guidance
          to help you prepare — not a guarantee of placement.
        </p>
      </LegalSection>

      <LegalSection heading="You remain responsible for published content">
        <p>
          You are responsible for the content published to your websites, including accuracy,
          claims, compliance with local regulations and any third-party rights. High-risk claims
          should be reviewed by a qualified professional.
        </p>
      </LegalSection>

      <LegalSection heading="EU AI Act transparency">
        <p>
          In line with Regulation (EU) 2024/1689 (the AI Act), Article 50(1): the drafts,
          opportunities, audits, scores and images Milo produces are generated by
          artificial-intelligence systems. Milo is a drafting and planning tool with a
          human-approval workflow — you review, edit and approve content before it is published.
        </p>
        <p>
          Machine-readable marking of AI-generated content (Article 50(2)) is being implemented
          ahead of the applicable compliance deadline. AI-generated images may carry provenance
          watermarks from the underlying model provider.
        </p>
        <p>
          A note on AI literacy (Article 4): AI-generated text and images can look confident while
          being wrong. The most effective control is the one already built into the workflow — read
          the draft, verify facts and claims against your own knowledge of your business, and
          approve only what you would stand behind.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
