import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, LegalSection } from "@/components/LegalPage";

export const Route = createFileRoute("/ai-disclaimer")({
  head: () => ({
    meta: [
      { title: "AI Content Disclaimer — Milo Growth" },
      { name: "description", content: "How Milo uses AI-assisted generation and your responsibilities when publishing." },
    ],
  }),
  component: AiDisclaimerPage,
});

function AiDisclaimerPage() {
  return (
    <LegalPage
      title="AI Content Disclaimer"
      intro="Milo uses AI to help you work faster — but AI output is a starting point, not a finished, verified result. Please read this before publishing AI-assisted content."
    >
      <LegalSection heading="Milo uses AI-assisted generation">
        <p>
          Milo uses AI-assisted generation to produce drafts, opportunities, audits and analyses based on the
          information you provide. These outputs are generated by automated models.
        </p>
      </LegalSection>

      <LegalSection heading="Outputs may need review">
        <p>
          AI outputs may be incomplete, inaccurate or unsuitable without review. Always review generated content
          before using or publishing it.
        </p>
      </LegalSection>

      <LegalSection heading="Auto-publish is optional and user-controlled">
        <p>
          Publishing to your website is something you control. Auto-publish is optional and only publishes content
          you have approved. Enable it only when you are comfortable publishing approved content automatically, and
          remember you remain responsible for reviewing content and claims before publishing.
        </p>
      </LegalSection>

      <LegalSection heading="Not professional advice">
        <p>
          Milo does not provide legal, medical, financial or other professional advice. Content that touches
          regulated topics, prices, health, finance or legal matters should be reviewed by a qualified
          professional before publishing.
        </p>
      </LegalSection>

      <LegalSection heading="No ranking or visibility guarantees">
        <p>
          Milo does not guarantee search rankings, traffic, conversions or revenue, and does not guarantee
          visibility or citation in AI tools. AI / search readiness features are guidance to help you prepare —
          not a guarantee of placement.
        </p>
      </LegalSection>

      <LegalSection heading="You remain responsible for published content">
        <p>
          You are responsible for the content published to your websites, including accuracy, claims, compliance
          with local regulations and any third-party rights. High-risk claims should be reviewed by a qualified
          professional.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
