/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubprocessorsRouteImport } from './routes/subprocessors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MiloAnalyticsDotjsRouteImport } from './routes/milo-analytics[.]js'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiDisclaimerRouteImport } from './routes/ai-disclaimer'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogLocalSeoGuideRouteImport } from './routes/blog.local-seo-guide'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiAnalyticsTrackRouteImport } from './routes/api.analytics.track'
import { Route as AuthenticatedAppSetupRouteImport } from './routes/_authenticated/app.setup'
import { Route as AuthenticatedAppServicesRouteImport } from './routes/_authenticated/app.services'
import { Route as AuthenticatedAppOpportunitiesRouteImport } from './routes/_authenticated/app.opportunities'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppEditorRouteImport } from './routes/_authenticated/app.editor'
import { Route as AuthenticatedAppCompetitorsRouteImport } from './routes/_authenticated/app.competitors'
import { Route as AuthenticatedAppCalendarRouteImport } from './routes/_authenticated/app.calendar'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppAuthorityRouteImport } from './routes/_authenticated/app.authority'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app.audit'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppAiVisibilityRouteImport } from './routes/_authenticated/app.ai-visibility'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubprocessorsRoute = SubprocessorsRouteImport.update({
  id: '/subprocessors',
  path: '/subprocessors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MiloAnalyticsDotjsRoute = MiloAnalyticsDotjsRouteImport.update({
  id: '/milo-analytics.js',
  path: '/milo-analytics.js',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDisclaimerRoute = AiDisclaimerRouteImport.update({
  id: '/ai-disclaimer',
  path: '/ai-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLocalSeoGuideRoute = BlogLocalSeoGuideRouteImport.update({
  id: '/blog/local-seo-guide',
  path: '/blog/local-seo-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsTrackRoute = ApiAnalyticsTrackRouteImport.update({
  id: '/api/analytics/track',
  path: '/api/analytics/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSetupRoute = AuthenticatedAppSetupRouteImport.update({
  id: '/app/setup',
  path: '/app/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppServicesRoute =
  AuthenticatedAppServicesRouteImport.update({
    id: '/app/services',
    path: '/app/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOpportunitiesRoute =
  AuthenticatedAppOpportunitiesRouteImport.update({
    id: '/app/opportunities',
    path: '/app/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/app/onboarding',
    path: '/app/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEditorRoute = AuthenticatedAppEditorRouteImport.update({
  id: '/app/editor',
  path: '/app/editor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCompetitorsRoute =
  AuthenticatedAppCompetitorsRouteImport.update({
    id: '/app/competitors',
    path: '/app/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCalendarRoute =
  AuthenticatedAppCalendarRouteImport.update({
    id: '/app/calendar',
    path: '/app/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAuthorityRoute =
  AuthenticatedAppAuthorityRouteImport.update({
    id: '/app/authority',
    path: '/app/authority',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/app/analytics',
    path: '/app/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAiVisibilityRoute =
  AuthenticatedAppAiVisibilityRouteImport.update({
    id: '/app/ai-visibility',
    path: '/app/ai-visibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/milo-analytics.js': typeof MiloAnalyticsDotjsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog/local-seo-guide': typeof BlogLocalSeoGuideRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/ai-visibility': typeof AuthenticatedAppAiVisibilityRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/authority': typeof AuthenticatedAppAuthorityRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/app/editor': typeof AuthenticatedAppEditorRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/setup': typeof AuthenticatedAppSetupRoute
  '/api/analytics/track': typeof ApiAnalyticsTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/milo-analytics.js': typeof MiloAnalyticsDotjsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog/local-seo-guide': typeof BlogLocalSeoGuideRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/ai-visibility': typeof AuthenticatedAppAiVisibilityRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/authority': typeof AuthenticatedAppAuthorityRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/app/editor': typeof AuthenticatedAppEditorRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/app/services': typeof AuthenticatedAppServicesRoute
  '/app/setup': typeof AuthenticatedAppSetupRoute
  '/api/analytics/track': typeof ApiAnalyticsTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/milo-analytics.js': typeof MiloAnalyticsDotjsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog/local-seo-guide': typeof BlogLocalSeoGuideRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/app/ai-visibility': typeof AuthenticatedAppAiVisibilityRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/authority': typeof AuthenticatedAppAuthorityRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/_authenticated/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/_authenticated/app/editor': typeof AuthenticatedAppEditorRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/_authenticated/app/services': typeof AuthenticatedAppServicesRoute
  '/_authenticated/app/setup': typeof AuthenticatedAppSetupRoute
  '/api/analytics/track': typeof ApiAnalyticsTrackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-disclaimer'
    | '/auth'
    | '/cookies'
    | '/dpa'
    | '/milo-analytics.js'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/sitemap.xml'
    | '/subprocessors'
    | '/terms'
    | '/unsubscribe'
    | '/blog/local-seo-guide'
    | '/email/unsubscribe'
    | '/app/ai-visibility'
    | '/app/analytics'
    | '/app/audit'
    | '/app/authority'
    | '/app/billing'
    | '/app/calendar'
    | '/app/competitors'
    | '/app/editor'
    | '/app/onboarding'
    | '/app/opportunities'
    | '/app/services'
    | '/app/setup'
    | '/api/analytics/track'
    | '/lovable/email/suppression'
    | '/app/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-disclaimer'
    | '/auth'
    | '/cookies'
    | '/dpa'
    | '/milo-analytics.js'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/sitemap.xml'
    | '/subprocessors'
    | '/terms'
    | '/unsubscribe'
    | '/blog/local-seo-guide'
    | '/email/unsubscribe'
    | '/app/ai-visibility'
    | '/app/analytics'
    | '/app/audit'
    | '/app/authority'
    | '/app/billing'
    | '/app/calendar'
    | '/app/competitors'
    | '/app/editor'
    | '/app/onboarding'
    | '/app/opportunities'
    | '/app/services'
    | '/app/setup'
    | '/api/analytics/track'
    | '/lovable/email/suppression'
    | '/app'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-disclaimer'
    | '/auth'
    | '/cookies'
    | '/dpa'
    | '/milo-analytics.js'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/sitemap.xml'
    | '/subprocessors'
    | '/terms'
    | '/unsubscribe'
    | '/blog/local-seo-guide'
    | '/email/unsubscribe'
    | '/_authenticated/app/ai-visibility'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/authority'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/calendar'
    | '/_authenticated/app/competitors'
    | '/_authenticated/app/editor'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/opportunities'
    | '/_authenticated/app/services'
    | '/_authenticated/app/setup'
    | '/api/analytics/track'
    | '/lovable/email/suppression'
    | '/_authenticated/app/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiDisclaimerRoute: typeof AiDisclaimerRoute
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  DpaRoute: typeof DpaRoute
  MiloAnalyticsDotjsRoute: typeof MiloAnalyticsDotjsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubprocessorsRoute: typeof SubprocessorsRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BlogLocalSeoGuideRoute: typeof BlogLocalSeoGuideRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiAnalyticsTrackRoute: typeof ApiAnalyticsTrackRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subprocessors': {
      id: '/subprocessors'
      path: '/subprocessors'
      fullPath: '/subprocessors'
      preLoaderRoute: typeof SubprocessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milo-analytics.js': {
      id: '/milo-analytics.js'
      path: '/milo-analytics.js'
      fullPath: '/milo-analytics.js'
      preLoaderRoute: typeof MiloAnalyticsDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-disclaimer': {
      id: '/ai-disclaimer'
      path: '/ai-disclaimer'
      fullPath: '/ai-disclaimer'
      preLoaderRoute: typeof AiDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/local-seo-guide': {
      id: '/blog/local-seo-guide'
      path: '/blog/local-seo-guide'
      fullPath: '/blog/local-seo-guide'
      preLoaderRoute: typeof BlogLocalSeoGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/track': {
      id: '/api/analytics/track'
      path: '/api/analytics/track'
      fullPath: '/api/analytics/track'
      preLoaderRoute: typeof ApiAnalyticsTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/setup': {
      id: '/_authenticated/app/setup'
      path: '/app/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AuthenticatedAppSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/services': {
      id: '/_authenticated/app/services'
      path: '/app/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AuthenticatedAppServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/opportunities': {
      id: '/_authenticated/app/opportunities'
      path: '/app/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AuthenticatedAppOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/editor': {
      id: '/_authenticated/app/editor'
      path: '/app/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AuthenticatedAppEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/competitors': {
      id: '/_authenticated/app/competitors'
      path: '/app/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AuthenticatedAppCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/calendar': {
      id: '/_authenticated/app/calendar'
      path: '/app/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AuthenticatedAppCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/authority': {
      id: '/_authenticated/app/authority'
      path: '/app/authority'
      fullPath: '/app/authority'
      preLoaderRoute: typeof AuthenticatedAppAuthorityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ai-visibility': {
      id: '/_authenticated/app/ai-visibility'
      path: '/app/ai-visibility'
      fullPath: '/app/ai-visibility'
      preLoaderRoute: typeof AuthenticatedAppAiVisibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAiVisibilityRoute: typeof AuthenticatedAppAiVisibilityRoute
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppAuthorityRoute: typeof AuthenticatedAppAuthorityRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppCalendarRoute: typeof AuthenticatedAppCalendarRoute
  AuthenticatedAppCompetitorsRoute: typeof AuthenticatedAppCompetitorsRoute
  AuthenticatedAppEditorRoute: typeof AuthenticatedAppEditorRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppOpportunitiesRoute: typeof AuthenticatedAppOpportunitiesRoute
  AuthenticatedAppServicesRoute: typeof AuthenticatedAppServicesRoute
  AuthenticatedAppSetupRoute: typeof AuthenticatedAppSetupRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAiVisibilityRoute: AuthenticatedAppAiVisibilityRoute,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppAuthorityRoute: AuthenticatedAppAuthorityRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppCalendarRoute: AuthenticatedAppCalendarRoute,
  AuthenticatedAppCompetitorsRoute: AuthenticatedAppCompetitorsRoute,
  AuthenticatedAppEditorRoute: AuthenticatedAppEditorRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppOpportunitiesRoute: AuthenticatedAppOpportunitiesRoute,
  AuthenticatedAppServicesRoute: AuthenticatedAppServicesRoute,
  AuthenticatedAppSetupRoute: AuthenticatedAppSetupRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiDisclaimerRoute: AiDisclaimerRoute,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  DpaRoute: DpaRoute,
  MiloAnalyticsDotjsRoute: MiloAnalyticsDotjsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubprocessorsRoute: SubprocessorsRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BlogLocalSeoGuideRoute: BlogLocalSeoGuideRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiAnalyticsTrackRoute: ApiAnalyticsTrackRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
